<?php /* _\|/_
         (o o)
+-----oOO-{_}-OOo--------------------------------------------------------+
| toendaCMS - Content Management and Weblogging System with XML and SQL  |
+------------------------------------------------------------------------+
| Copyright (c) Toenda Software Development                              |
| Author: Jonathan Naumann                                               |
+------------------------------------------------------------------------+
|
| toendaCMS Export class
|
| File:	tcms_export.lib.php
|
+
*/


defined('_TCMS_VALID') or die('Restricted access');


/**
 * toendaCMS Export class
 *
 * This class is used to provide a export class.
 *
 * @version 0.0.1
 * @author	Jonathan Naumann <jonathan@toenda.com>
 * @package toendaCMS
 * @subpackage tcms_kernel
 *
 * <code>
 * 
 * Methods
 *
 * --------------------------------------------------------
 * CONSTRUCTOR AND DESTRUCTOR
 * --------------------------------------------------------
 * 
 * __construct                 -> Constructor
 * __destruct                  -> Destructor
 * 
 * --------------------------------------------------------
 * PROPERTIES
 * --------------------------------------------------------
 * 
 * setTcmsTimeObj              -> Set the tcms_time object
 *
 * --------------------------------------------------------
 * PUBLIC METHODS
 * --------------------------------------------------------
 * 
 * importVCard                 -> Import a vcard
 * 
 * </code>
 *
 */


class tcms_export extends tcms_main {
	private $m_administer;
	private $m_charset;
	private $_tcmsTime;
	
	// database information
	private $db_choosenDB;
	private $db_user;
	private $db_pass;
	private $db_host;
	private $db_database;
	private $db_port;
	private $db_prefix;
	
	
	
	/**
	 * PHP5: Default constructor
	 *
	 * @param String $administer
	 * @param String $charset
	 * @param Object $tcmsTimeObj = null
	 */
	public function __construct($administer, $charset, $tcmsTimeObj = null){
		$this->m_administer = $administer;
		$this->administer = $administer;
		$this->m_charset = $charset;
		$this->_tcmsTime = $tcmsTimeObj;
		
		require($this->m_administer.'/tcms_global/database.php');
		
		$this->db_choosenDB = $tcms_db_engine;
		$this->db_user      = $tcms_db_user;
		$this->db_pass      = $tcms_db_password;
		$this->db_host      = $tcms_db_host;
		$this->db_database  = $tcms_db_database;
		$this->db_port      = $tcms_db_port;
		$this->db_prefix    = $tcms_db_prefix;
	}
	
	
	
	/**
	 * PHP5 Destructor
	 */
	public function __destruct(){
	}
	
	
	
	// -------------------------------------------------
	// PROPERTIES
	// -------------------------------------------------
	
	
	
	/**
	 * Set the tcms_time object
	 *
	 * @param Object $value
	 */
	public function setTcmsTimeObj($value) {
		$this->_tcmsTime = $value;
	}
	
	
	
	// -------------------------------------------------
	// PUBLIC MEMBERS
	// -------------------------------------------------
	
	
	
	/**
	 * Generate a Wordpress Export file
	 * 
	 * @return String XML-Stream
	 */
	public function generateWordpressExportFile() {
		$xml = '<?xml version="1.0" encoding="UTF-8"?>'.chr(13);
		$xml .= '<!-- generator="toendaCMS '.$cms_version.' - '.$cms_build.'" created="'.date('Y-m-d H:i').'"-->'.chr(13);
		$xml .= '<rss version="2.0"'.chr(13);
	    $xml .= $this->createCharString(4).'xmlns:content="http://purl.org/rss/1.0/modules/content/"'.chr(13);
	    $xml .= $this->createCharString(4).'xmlns:wfw="http://wellformedweb.org/CommentAPI/"'.chr(13);
	    $xml .= $this->createCharString(4).'xmlns:dc="http://purl.org/dc/elements/1.1/"'.chr(13);
	    $xml .= $this->createCharString(4).'xmlns:wp="http://wordpress.org/export/1.0/"'.chr(13);
	    $xml .= '>'.chr(13);
		$xml .= $this->createCharString(4).'<channel>'.chr(13);
		$xml .= $this->createCharString(4).'</channel>'.chr(13);
		$xml .= '</rss>'.chr(13);
		
		return $xml;
		
		/*
		<?xml version="1.0" encoding="UTF-8"?>
<!-- This is a WordPress eXtended RSS file generated by WordPress as an export of your blog. -->
<!-- It contains information about your blog's posts, comments, and categories. -->
<!-- You may use this file to transfer that content from one site to another. -->
<!-- This file is not intended to serve as a complete backup of your blog. -->

<!-- To import this information into a WordPress blog follow these steps. -->
<!-- 1. Log into that blog as an administrator. -->
<!-- 2. Go to Manage: Import in the blog's admin panels. -->
<!-- 3. Choose "WordPress" from the list. -->
<!-- 4. Upload this file using the form provided on that page. -->
<!-- 5. You will first be asked to map the authors in this export file to users -->
<!--    on the blog.  For each author, you may choose to map to an -->
<!--    existing user on the blog or to create a new user -->
<!-- 6. WordPress will then import each of the posts, comments, and categories -->
<!--    contained in this file into your blog -->

<!-- generator="WordPress/2.6-RC1" created="2008-07-14 15:29"-->
<rss version="2.0"
    xmlns:content="http://purl.org/rss/1.0/modules/content/"
    xmlns:wfw="http://wellformedweb.org/CommentAPI/"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:wp="http://wordpress.org/export/1.0/"
>

<channel>
    <title>galaxy Blog</title>
    <link>http://galaxy.vandango.org</link>
    <description>Just another WordPress weblog</description>
    <pubDate>Mon, 14 Jul 2008 13:28:10 +0000</pubDate>
    <generator>http://wordpress.org/?v=2.6-RC1</generator>
    <language>en</language>
    <wp:wxr_version>1.0</wp:wxr_version>
    <wp:base_site_url>http://galaxy.vandango.org</wp:base_site_url>
    <wp:base_blog_url>http://galaxy.vandango.org</wp:base_blog_url>
    <wp:category><wp:category_nicename>uncategorized</wp:category_nicename><wp:category_parent></wp:category_parent><wp:cat_name><![CDATA[Uncategorized]]></wp:cat_name></wp:category>
    <wp:tag><wp:tag_slug>hello</wp:tag_slug><wp:tag_name><![CDATA[Hello]]></wp:tag_name></wp:tag>
    <wp:tag><wp:tag_slug>post</wp:tag_slug><wp:tag_name><![CDATA[Post]]></wp:tag_name></wp:tag>
    <wp:tag><wp:tag_slug>test</wp:tag_slug><wp:tag_name><![CDATA[Test]]></wp:tag_name></wp:tag>
    <wp:tag><wp:tag_slug>test-post</wp:tag_slug><wp:tag_name><![CDATA[Test Post]]></wp:tag_name></wp:tag>
        <item>
<title>Hello world!</title>
<link>http://galaxy.vandango.org/archives/1</link>
<pubDate>Fri, 04 Jul 2008 12:00:38 +0000</pubDate>
<dc:creator><![CDATA[vandango]]></dc:creator>

        <category><![CDATA[Uncategorized]]></category>

        <category domain="category" nicename="uncategorized"><![CDATA[Uncategorized]]></category>

        <category domain="tag"><![CDATA[Hello]]></category>

        <category domain="tag" nicename="hello"><![CDATA[Hello]]></category>

<guid isPermaLink="false">http://galaxy.vandango.org/?p=1</guid>
<description></description>
<content:encoded><![CDATA[Welcome to WordPress. This is your first post. Edit or delete it, then start blogging!]]></content:encoded>
<excerpt:encoded><![CDATA[]]></excerpt:encoded>
<wp:post_id>1</wp:post_id>
<wp:post_date>2008-07-04 14:00:38</wp:post_date>
<wp:post_date_gmt>2008-07-04 12:00:38</wp:post_date_gmt>
<wp:comment_status>open</wp:comment_status>
<wp:ping_status>open</wp:ping_status>
<wp:post_name>hello-world</wp:post_name>
<wp:status>publish</wp:status>
<wp:post_parent>0</wp:post_parent>
<wp:menu_order>0</wp:menu_order>
<wp:post_type>post</wp:post_type>
<wp:post_password></wp:post_password>
<wp:postmeta>
<wp:meta_key>_edit_lock</wp:meta_key>
<wp:meta_value>1215175430</wp:meta_value>
</wp:postmeta>
<wp:postmeta>
<wp:meta_key>_edit_last</wp:meta_key>
<wp:meta_value>1</wp:meta_value>
</wp:postmeta>
<wp:comment>
<wp:comment_id>1</wp:comment_id>
<wp:comment_author><![CDATA[Mr WordPress]]></wp:comment_author>
<wp:comment_author_email></wp:comment_author_email>
<wp:comment_author_url>http://wordpress.org/</wp:comment_author_url>
<wp:comment_author_IP></wp:comment_author_IP>
<wp:comment_date>2008-07-04 14:00:38</wp:comment_date>
<wp:comment_date_gmt>2008-07-04 12:00:38</wp:comment_date_gmt>
<wp:comment_content><![CDATA[Hi, this is a comment.<br />To delete a comment, just log in and view the post&#039;s comments. There you will have the option to edit or delete them.]]></wp:comment_content>
<wp:comment_approved>1</wp:comment_approved>
<wp:comment_type></wp:comment_type>
<wp:comment_parent>0</wp:comment_parent>
<wp:comment_user_id>0</wp:comment_user_id>
</wp:comment>
    </item>
<item>
<title>About</title>
<link>http://galaxy.vandango.org/about</link>
<pubDate>Fri, 04 Jul 2008 12:00:38 +0000</pubDate>
<dc:creator><![CDATA[vandango]]></dc:creator>

<guid isPermaLink="false">http://galaxy.vandango.org/?page_id=2</guid>
<description></description>
<content:encoded><![CDATA[This is an example of a WordPress page, you could edit this to put information about yourself or your site so readers know where you are coming from. You can create as many pages like this one or sub-pages as you like and manage all of your content inside of WordPress.]]></content:encoded>
<excerpt:encoded><![CDATA[]]></excerpt:encoded>
<wp:post_id>2</wp:post_id>
<wp:post_date>2008-07-04 14:00:38</wp:post_date>
<wp:post_date_gmt>2008-07-04 12:00:38</wp:post_date_gmt>
<wp:comment_status>open</wp:comment_status>
<wp:ping_status>open</wp:ping_status>
<wp:post_name>about</wp:post_name>
<wp:status>publish</wp:status>
<wp:post_parent>0</wp:post_parent>
<wp:menu_order>0</wp:menu_order>
<wp:post_type>page</wp:post_type>
<wp:post_password></wp:post_password>
    </item>
<item>
<title>Hello world!</title>
<link>http://galaxy.vandango.org/archives/9</link>
<pubDate>Fri, 04 Jul 2008 12:00:38 +0000</pubDate>
<dc:creator><![CDATA[vandango]]></dc:creator>

        <category><![CDATA[Uncategorized]]></category>

        <category domain="category" nicename="uncategorized"><![CDATA[Uncategorized]]></category>

<guid isPermaLink="false">http://galaxy.vandango.org/?p=9</guid>
<description></description>
<content:encoded><![CDATA[Welcome to WordPress. This is your first post. Edit or delete it, then start blogging!]]></content:encoded>
<excerpt:encoded><![CDATA[]]></excerpt:encoded>
<wp:post_id>9</wp:post_id>
<wp:post_date>2008-07-04 14:00:38</wp:post_date>
<wp:post_date_gmt>2008-07-04 12:00:38</wp:post_date_gmt>
<wp:comment_status>open</wp:comment_status>
<wp:ping_status>open</wp:ping_status>
<wp:post_name>1-revision</wp:post_name>
<wp:status>inherit</wp:status>
<wp:post_parent>1</wp:post_parent>
<wp:menu_order>0</wp:menu_order>
<wp:post_type>revision</wp:post_type>
<wp:post_password></wp:post_password>
    </item>
<item>
<title>Test Post</title>
<link>http://galaxy.vandango.org/archives/4</link>
<pubDate>Fri, 04 Jul 2008 12:02:00 +0000</pubDate>
<dc:creator><![CDATA[vandango]]></dc:creator>

        <category><![CDATA[Uncategorized]]></category>

        <category domain="category" nicename="uncategorized"><![CDATA[Uncategorized]]></category>

<guid isPermaLink="false">http://galaxy.vandango.org/?p=4</guid>
<description></description>
<content:encoded><![CDATA[]]></content:encoded>
<excerpt:encoded><![CDATA[]]></excerpt:encoded>
<wp:post_id>4</wp:post_id>
<wp:post_date>2008-07-04 14:02:00</wp:post_date>
<wp:post_date_gmt>2008-07-04 12:02:00</wp:post_date_gmt>
<wp:comment_status>open</wp:comment_status>
<wp:ping_status>open</wp:ping_status>
<wp:post_name>3-revision</wp:post_name>
<wp:status>inherit</wp:status>
<wp:post_parent>3</wp:post_parent>
<wp:menu_order>0</wp:menu_order>
<wp:post_type>revision</wp:post_type>
<wp:post_password></wp:post_password>
    </item>
<item>
<title>Test Post</title>
<link>http://galaxy.vandango.org/archives/5</link>
<pubDate>Fri, 04 Jul 2008 12:02:17 +0000</pubDate>
<dc:creator><![CDATA[vandango]]></dc:creator>

        <category><![CDATA[Uncategorized]]></category>

        <category domain="category" nicename="uncategorized"><![CDATA[Uncategorized]]></category>

<guid isPermaLink="false">http://galaxy.vandango.org/?p=5</guid>
<description></description>
<content:encoded><![CDATA[asdasdsadsa]]></content:encoded>
<excerpt:encoded><![CDATA[]]></excerpt:encoded>
<wp:post_id>5</wp:post_id>
<wp:post_date>2008-07-04 14:02:17</wp:post_date>
<wp:post_date_gmt>2008-07-04 12:02:17</wp:post_date_gmt>
<wp:comment_status>open</wp:comment_status>
<wp:ping_status>open</wp:ping_status>
<wp:post_name>3-revision-2</wp:post_name>
<wp:status>inherit</wp:status>
<wp:post_parent>3</wp:post_parent>
<wp:menu_order>0</wp:menu_order>
<wp:post_type>revision</wp:post_type>
<wp:post_password></wp:post_password>
    </item>
<item>
<title>Test Post</title>
<link>http://galaxy.vandango.org/archives/3</link>
<pubDate>Fri, 04 Jul 2008 12:02:20 +0000</pubDate>
<dc:creator><![CDATA[vandango]]></dc:creator>

        <category><![CDATA[Uncategorized]]></category>

        <category domain="category" nicename="uncategorized"><![CDATA[Uncategorized]]></category>

        <category domain="tag"><![CDATA[Hello]]></category>

        <category domain="tag" nicename="hello"><![CDATA[Hello]]></category>

        <category domain="tag"><![CDATA[Post]]></category>

        <category domain="tag" nicename="post"><![CDATA[Post]]></category>

        <category domain="tag"><![CDATA[Test]]></category>

        <category domain="tag" nicename="test"><![CDATA[Test]]></category>

        <category domain="tag"><![CDATA[Test Post]]></category>

        <category domain="tag" nicename="test-post"><![CDATA[Test Post]]></category>

<guid isPermaLink="false">http://galaxy.vandango.org/?p=3</guid>
<description></description>
<content:encoded><![CDATA[asdasdsadsa]]></content:encoded>
<excerpt:encoded><![CDATA[]]></excerpt:encoded>
<wp:post_id>3</wp:post_id>
<wp:post_date>2008-07-04 14:02:20</wp:post_date>
<wp:post_date_gmt>2008-07-04 12:02:20</wp:post_date_gmt>
<wp:comment_status>open</wp:comment_status>
<wp:ping_status>open</wp:ping_status>
<wp:post_name>test-post</wp:post_name>
<wp:status>publish</wp:status>
<wp:post_parent>0</wp:post_parent>
<wp:menu_order>0</wp:menu_order>
<wp:post_type>post</wp:post_type>
<wp:post_password></wp:post_password>
<wp:postmeta>
<wp:meta_key>_edit_lock</wp:meta_key>
<wp:meta_value>1215687522</wp:meta_value>
</wp:postmeta>
<wp:postmeta>
<wp:meta_key>_edit_last</wp:meta_key>
<wp:meta_value>1</wp:meta_value>
</wp:postmeta>
    </item>
<item>
<title>Test Post</title>
<link>http://galaxy.vandango.org/archives/8</link>
<pubDate>Fri, 04 Jul 2008 12:02:20 +0000</pubDate>
<dc:creator><![CDATA[vandango]]></dc:creator>

        <category><![CDATA[Uncategorized]]></category>

        <category domain="category" nicename="uncategorized"><![CDATA[Uncategorized]]></category>

<guid isPermaLink="false">http://galaxy.vandango.org/?p=8</guid>
<description></description>
<content:encoded><![CDATA[asdasdsadsa]]></content:encoded>
<excerpt:encoded><![CDATA[]]></excerpt:encoded>
<wp:post_id>8</wp:post_id>
<wp:post_date>2008-07-04 14:02:20</wp:post_date>
<wp:post_date_gmt>2008-07-04 12:02:20</wp:post_date_gmt>
<wp:comment_status>open</wp:comment_status>
<wp:ping_status>open</wp:ping_status>
<wp:post_name>3-revision-3</wp:post_name>
<wp:status>inherit</wp:status>
<wp:post_parent>3</wp:post_parent>
<wp:menu_order>0</wp:menu_order>
<wp:post_type>revision</wp:post_type>
<wp:post_password></wp:post_password>
    </item>
<item>
<title>Test Post</title>
<link>http://galaxy.vandango.org/archives/10</link>
<pubDate>Fri, 04 Jul 2008 12:43:36 +0000</pubDate>
<dc:creator><![CDATA[vandango]]></dc:creator>

        <category><![CDATA[Uncategorized]]></category>

        <category domain="category" nicename="uncategorized"><![CDATA[Uncategorized]]></category>

<guid isPermaLink="false">http://galaxy.vandango.org/?p=10</guid>
<description></description>
<content:encoded><![CDATA[asdasdsadsa]]></content:encoded>
<excerpt:encoded><![CDATA[]]></excerpt:encoded>
<wp:post_id>10</wp:post_id>
<wp:post_date>2008-07-04 14:43:36</wp:post_date>
<wp:post_date_gmt>2008-07-04 12:43:36</wp:post_date_gmt>
<wp:comment_status>open</wp:comment_status>
<wp:ping_status>open</wp:ping_status>
<wp:post_name>3-revision-4</wp:post_name>
<wp:status>inherit</wp:status>
<wp:post_parent>3</wp:post_parent>
<wp:menu_order>0</wp:menu_order>
<wp:post_type>revision</wp:post_type>
<wp:post_password></wp:post_password>
    </item>
<item>
<title>Archives</title>
<link>http://galaxy.vandango.org/archivepage</link>
<pubDate>Mon, 14 Jul 2008 13:28:10 +0000</pubDate>
<dc:creator><![CDATA[vandango]]></dc:creator>

        <category><![CDATA[Uncategorized]]></category>

        <category domain="category" nicename="uncategorized"><![CDATA[Uncategorized]]></category>

<guid isPermaLink="false">http://galaxy.vandango.org/archivepage</guid>
<description></description>
<content:encoded><![CDATA[Do not edit this page]]></content:encoded>
<excerpt:encoded><![CDATA[Do not edit this page]]></excerpt:encoded>
<wp:post_id>13</wp:post_id>
<wp:post_date>2008-07-14 15:28:10</wp:post_date>
<wp:post_date_gmt>2008-07-14 13:28:10</wp:post_date_gmt>
<wp:comment_status>open</wp:comment_status>
<wp:ping_status>open</wp:ping_status>
<wp:post_name>archivepage</wp:post_name>
<wp:status>publish</wp:status>
<wp:post_parent>0</wp:post_parent>
<wp:menu_order>0</wp:menu_order>
<wp:post_type>page</wp:post_type>
<wp:post_password></wp:post_password>
    </item>
</channel>
</rss>
		*/
	}
}
